= I/O Stream

== FileReader/FileWriter

* FileReader
** Java에서 텍스트 파일(`.txt`)을 Java 프로그램으로 읽어올 수 있는 기능을 제공하는 클래스
** `FileReader`는 `InputStreamReader`의 하위타입이며, 상위타입의 Constructor에서  `InputStream`을 파라미터로 전달한다.
** 내부에 버퍼의 크기가 정해져 있지만 버퍼라고 할만한 저장공간이 존재하지 않는다. 사용자가 버퍼를 만들어 그 곳에 파일의 내용을 불러 오는 것 같다. 
*** `read` 메서드에서 `java.nio.CharBuffer` 타입의 파라미터를 입력받아 버퍼를 처리한다.
*** 실제로 파일에서 값을 가져오는 기능이 기술되어있는 것은 `StreamDecoder` 이다. 이 클래스에서 Buffer를 사용하여 값을 가져온다.

* FileWriter
** Java 프로그램의 출력이나 정보 등을 텍스트 파일(`.txt`)에 작성할 수 있는 기능을 제공하는 클래스
** `FileWriter`는 `OutputStreamWriter`의 하위타입이며, 상위타입의 Constructor에서  `OutputStream`을 파라미터로 전달한다.
** `Writer` 클래스에는 1KB의 데이터를 담을 수 있는 Buffer가 구현되어 있다. 해당 버퍼는 `Writer` 의 하위 타입인 `StreamEncdoer` 에서 값을 파일에 입력하는데 사용된다.

_예시를 보면 `FileReader` 경우, `InputStreamReader`, `InputStream` 의 호출을 통합하였다고 볼 수 있다. `FileWriter` 의 경우에도 `OutputStreamWriter`, `OutputStream` 의 호출을 통합하기 위해서 해당 클래스를 사용하는 것이라 볼 수 있다._

* 아래는 FileReader, FileWriter 소스파일에 들어있는 생성자 중 하나이다.

[source, java]
----
public class FileReader extends InputStreamReader {

    public FileReader(String fileName) throws FileNotFoundException {
        super(new FileInputStream(fileName));
    }
}
----

[source, java]
----
public class FileWriter extends OutputStreamWriter {

    public FileWriter(String fileName) throws IOException {
        super(new FileOutputStream(fileName));
    }
}
----

* 두 생성자가 발생시키는 오류(예외)가 다른 이유는?
** `FileReader` 생성자에서 발생하는 예외는 지정된 경로 혹은 파일의 이름에 해당하는 파일이 없을 경우에 발생하기 때문에 `FileNotFoundException` 이 발생한다. `FileWriter` 는 파일을 열고 내용을 수정하거나 추가하는 것 이외에 기존에 존재하지 않던 파일을 생성하여 값을 기록하기 때문에 `IOException` 이 발생한다고 할 수 있다.

* BufferedReader VS FileReader
** 두 클래스를 사용하는데 호출되는 클래스는 `InputStreamReader`, `InputStream` 으로 동일하다. 
** 두 클래스 모두 `Reader` 클래스에 존재하는 `StreamDecoder` 클래스의 `read()` 메서드를 사용하여 파일의 내용을 Java 프로그램으로 읽어온다. 이 클래스는 `sun.nio.cs` 패키지에 속해있으며, Buffer를 사용한다. 따라서 두 클래스 모두 Buffer를 사용함을 알 수 있다.

[source, java]
----
FileReader fileReader = new FileReader("test.txt");
BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(new FileInputStream("test.txt")));
----

== InputStream/OutputStream

* Stream
** 물리적인 데이터의 흐름 (순차적, 단방향)
** 바이너리 데이터의 흐름을 연결하기 위한 추상적인 통로
** byte 데이터를 `int` 형태로 저장한다.

_대부분의 경우에서 Java는 `byte` 의 흐름을 전달하기 위해서 Stream을 사용한다._

* `InputStream`
** 시스템의 특정한 Resource를 Java 프로그램으로 불러올 수 있는 데이터의 흐름을 추상화하여 Java의 클래스로 구성 +
→ Java 프로그램으로 데이터가 들어온다는 개념으로 생각
** Java에서 접근할 수 있는 다양한 Resource가 존재한다 이러한 Resource를 Java 프로그램으로 가져오는 통로를 단일화 한 것 
** Actual parameter로 전달된 Array를 버퍼로 사용, 해당 Index에 존재하는 파일의 내용을 순차적으로 남는다.
*** Array를 parameter로 전달하는 것은 배열이 위치한 곳의 메모리 주소를 전달하는 것과 마찬가지 이므로 해당 버퍼에는 Resource에서 읽어온 데이터로 채워져있다.
*** `abstract` 키워드로 선언되어 있기 때문에 구현하는 방법은 Resource의 종류에 따라서 달라질 수 있음을 암시한다.

[source, java]
----
public int read(byte b[], int off, int len) throws IOException {
    Objects.checkFromIndexSize(off, len, b.length);
    if (len == 0) {
        return 0;
    }

    int c = read();
    if (c == -1) {
        return -1;
    }
    b[off] = (byte)c;

    int i = 1;
    try {
        for (; i < len ; i++) {
            c = read(); // abstract로 정의된 메서드
            if (c == -1) {
                break;
            }
            b[off + i] = (byte)c;
        }
    } catch (IOException ee) {
    }
    return i;
}
----

* `OutputStream`
** Java 프로그램에서 발생한 데이터들을 시스템의 Resource로 전송할 수 있게 하는 데이터의 흐름을 추상화하여 Java의  클래스로 구성 +
→ Java 프로그램에서 생성된 데이터가 연결된 Resource로 나가는 개념으로 생각 
** Java 프로그램이 동작하면서 생성된 다양한 형태의 데이터들을 연결된 Resource으로 전송 하기위한 통로를 단일화 한 것
** Actual parameter로 전달된 Array를 버퍼로 Resource로 이동시킬 데이터(byte)를 보관한다. 
*** Array를 parameter로 전달하는 것은 배열이 위치한 곳의 메모리 주소를 전달하는 것과 마찬가지 이므로 해당 버퍼에는 Java 프로그램에서 읽어온 데이터로 채워져있다.
*** `abstract` 키워드로 선언되어 있기 때문에 구현하는 방법은 Resource의 종류에 따라서 달라질 수 있음을 암시한다.

[source, java]
----
public void write(byte b[], int off, int len) throws IOException {
    Objects.checkFromIndexSize(off, len, b.length);
    // len == 0 condition implicitly handled by loop bounds
    for (int i = 0 ; i < len ; i++) {
        write(b[off + i]);
    }
}
----

== InputStreamReader/OutputStreamWriter

* `InputStreamReader`
** InputStream에 기록된 byte를 유니코드의 문자형태로 변환한다.
** 내부적으로 `CharsetDecoder` 의 `public final CoderResult decode(ByteBuffer in, CharBuffer out, boolean endOfInput)` 메서드를 사용하여 byte를 문자로 변환한다.

* `OutputStreamWriter`
** OuputStream에 기록된 문자열을 byte의 형태로 변환한다.
** 내부적으로 `CharsetEncoder` 의 `public final CoderResult encode(CharBuffer in, ByteBuffer out, boolean endOfInput)` 메서드를 사용하여 문자를 byte로 변환한다.

== File과 File Descripter

* File
** File 타입은 실제 파일이나 디렉토리의 경로 또는 참조를 추상화한 타입이다. 실제로 Secondary memory에 저장되는 데이터를 의미하는 것이 아니다.
** 물리적인 FileSystem에 File 객체가 가지고 있는 경로를 확인하고 OS에 존재하는 실제 File 혹은 Directory와 대응되는지 확인할 때 사용한다.
*** 위에서의 기술된 이유로 `FileInputStream`, `FileOutputStream` 을 생성할 때, 실제 파일과 I/O Stream의 연결이 정상적인지 확인이 가능하다.

* File Descriptor.footnote:[https://dev-ahn.tistory.com/96]
** Unix 계열 OS에서 어떠한 Process가 파일에 접근하기 위해서 사용하는 양의 정수값
*** 프로세스가 해당 파일에 접근하기 위해 파일의 메모리 주소?를 테이블의 형태로 보관하는데 이 주소에 접근하기 위해서 필요한 index를 `File Descriptor` 라고 한다.
** Process가 실행 중에 File을 열면 현재 사용 중이지 않은 정수 중, 가장 적은 값을 파일에 할당한다.
*** 프로그램이 메모리에서 실행 될 때, 기본적으로 할당 되어있는 File Descriptor 값이 존재한다.
**** Standard Input: `0`
**** Standard Output: `1`
**** Standard Error : `2`

** Java 에서의 File Descriptor는?
*** Java 11 API 문서.footnote:[https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/FileDescriptor.html]에 따르면, +
`The main practical use for a file descriptor is to create a FileInputStream or FileOutputStream to contain it.` 이라고 적혀있는데 File I/O Stream을 생성하는데 주로 사용된다고 한다. 그렇다면 JVM을 일종의 프로세스라고 한다면, JVM에서 필요한 파일 등을 사용할 수 있게 해당 파일의 메모리 위치를 기록하고 있는 값을 참조하기 위한 index로 볼 수 있을 것이다.

== flush()를 명시적으로 호출하지 않아도 되는 이유는?

** `StreamEncoder` 클래스 내부에서 데이터를 파일에 기록하도록 정의된 메서드는 `implWrite(CharBuffer cb)` 이다.
** 이 메서드에서 파일에 기록하기 전에 버퍼에 남아있는 데이터를 발견하면, `flushLeftoverChar(cb, false)` 메서드를 통해서 Buffer에 남아있는 데이터를 파일에다가 기록하는 것을 알 수 있다.
** Buffer에 존재하는 데이터를 파일에 기록하다가 Buffer가 최소로 표현할 수 있는 단위의 한계보다 적은 위치에 문자가 존재한다면, 해당 문자를 Buffer로 다시 가져와서 기록한다. 이렇게 버퍼의 내용을 파일에 기록하면서 flush가 같이 기능함을 알 수 있다.

[source, java]
----
// OutputStreamWriter 메서드
public void write(char cbuf[], int off, int len) throws IOException {
    se.write(cbuf, off, len); // StreamEncoder se;
}
----

[source, java]
----
// StreamEncoder 메서드
void implWrite(CharBuffer cb) throws IOException
{
    if (haveLeftoverChar) {
        flushLeftoverChar(cb, false);
    }

    while (cb.hasRemaining()) {
        CoderResult cr = encoder.encode(cb, bb, false);
        if (cr.isUnderflow()) {
            assert (cb.remaining() <= 1) : cb.remaining();
            if (cb.remaining() == 1) {
                haveLeftoverChar = true;
                leftoverChar = cb.get();
            }
            break;
        }
        if (cr.isOverflow()) {
            assert bb.position() > 0;
            writeBytes();
            continue;
        }
        cr.throwException();
    }
}

private void flushLeftoverChar(CharBuffer cb, boolean endOfInput) throws IOException
{
    if (!haveLeftoverChar && !endOfInput)
        return;
    if (lcb == null)
        lcb = CharBuffer.allocate(2);
    else
        lcb.clear();
    if (haveLeftoverChar)
        lcb.put(leftoverChar);
    if ((cb != null) && cb.hasRemaining())
        lcb.put(cb.get());
    lcb.flip();
    while (lcb.hasRemaining() || endOfInput) {
        CoderResult cr = encoder.encode(lcb, bb, endOfInput);
        if (cr.isUnderflow()) {
            if (lcb.hasRemaining()) {
                leftoverChar = lcb.get();
                if (cb != null && cb.hasRemaining()) {
                    lcb.clear();
                    lcb.put(leftoverChar).put(cb.get()).flip();
                    continue;
                }
                return;
            }
            break;
        }
        if (cr.isOverflow()) {
            assert bb.position() > 0;
            writeBytes();
            continue;
        }
        cr.throwException();
    }
    haveLeftoverChar = false;
}
----

== I/O Stream을 `close()` 하지 않는다면 발생하는 일

* I/O Stream을 닫지 않으면 추후에 사용할 리소스가 부족할 수 있다.
** File Descriptor Table에 Resource의 주소를 저장하는데 Table의 한계를 초과하면 더 이상 Resource에 접근할 수 없음.
*** 개인만 해당 프로세스를 사용하는 경우에는 잘 발생하지 않지만, 여러 사용자가 프로세스를 동시에 사용하는 경우에는 생각보다 자주 일어나는 현상이라함.
*** 메모리 주소를 보관하는 Table의 크기를 동적으로 변경하여 해당 현상을 방지할 수 있음.

* File의 확실한 종료를 프로그래머가 보장하지 않는다면, `Resource Leak`이 발생할 수 있다.
** Resource leak으로 인하여 Resource를 참조할 수 없어 `DoS` 을 받을 경우 취약하다.
*** 의도적으로 `close()` 가 사용되지 않은 메서드를 반복적으로 호출하여 시스템의 예기치 못한 종료를 유발한다.

* Concurrency 상황에서는 Resource를 선점(Lock)하고 연산이 진행되기 때문에 사용한 Resource를 닫혀있지 않다면, 다른 메서드나 객체 등이 해당 Resource에 접근하지 못하는 상황이 발생한다.footnote:[https://velog.io/@jsj3282/9.-IO%EC%97%90%EC%84%9C-%EB%B0%9C%EC%83%9D%ED%95%98%EB%8A%94-%EB%B3%91%EB%AA%A9-%ED%98%84%EC%83%81]
** 해당 Resource를 Reading 하는 것은 크게 문제가 되지 않지만 Writing 하는 상황에서는 Dirty-Read, Phantom Read 등의 문제가 발생할 수 있다.

[source, java]
----
// Writer 클래스의 일부
protected Object lock;

protected Writer() {
    this.lock = this;
}

public void write(String str, int off, int len) throws IOException {
    synchronized (lock) {
        char cbuf[];
        if (len <= WRITE_BUFFER_SIZE) {
            if (writeBuffer == null) {
                writeBuffer = new char[WRITE_BUFFER_SIZE];
            }
            cbuf = writeBuffer;
        } else {    // Don't permanently allocate very large buffers.
            cbuf = new char[len];
        }
        str.getChars(off, (off + len), cbuf, 0);
        write(cbuf, 0, len);
    }
}
----

== File의 Lifecycle
=== File의 상태확인

* File을 통해서 지정된 경로에 파일 혹은 디렉토리가 존재하는지 확인 후, 그 정보를 가져온다.
** File I/O Stream을 구성할 때, 파일이 존재하는지 확인하기 위해서 사용된다.

* File Descriptor로 Java 프로그램에 시스템에 물리적으로 존재하는 파일의 주소를 가져온다.
** JVM의 PCB에 존재하는 Table에 File Descriptor 번호와 해당되는 파일의 메모리 주소를 저장한다.


[source, java]
----
public FileInputStream(String name) throws FileNotFoundException {
    this(name != null ? new File(name) : null);
}

public FileInputStream(File file) throws FileNotFoundException {
    String name = (file != null ? file.getPath() : null);
    SecurityManager security = System.getSecurityManager();
    if (security != null) {
        security.checkRead(name);
    }
    if (name == null) {
        throw new NullPointerException();
    }
    if (file.isInvalid()) {
        throw new FileNotFoundException("Invalid file path");
    }
    fd = new FileDescriptor();
    fd.attach(this);
    path = name;
    open(name);
    altFinalizer = getFinalizer(this);
    if (altFinalizer == null) {
        FileCleanable.register(fd);       // open set the fd, register the cleanup
    }
}
----

=== Stream으로 Java 프로그램과 디스크에 존재하는 파일 연결

* File I/O Stream을 생성하고 File Descripter 값을 통해, File Desciptor Table에 존재하는 특정한 파일의 메모리 주소에 참조하여 Java 프로그램과 해당 파일을 Stream으로 연결한다.

[source, java]
----
public FileInputStream(FileDescriptor fdObj) {
    SecurityManager security = System.getSecurityManager();
    if (fdObj == null) {
        throw new NullPointerException();
    }
    if (security != null) {
        security.checkRead(fdObj);
    }
    fd = fdObj;
    path = null;
    altFinalizer = null;

    /*
        * FileDescriptor is being shared by streams.
        * Register this stream with FileDescriptor tracker.
        */
    fd.attach(this);
}
----

=== 기능 수행

* InputStreamReader, OutputStreamWriter로 Byte stream을 Character stream으로 변경한다.
** File I/O Stream의 ByteStream을 우리가 읽을 수 있는 문자로 읽기 위해서는 InputStreamReader로 변환작업을 거쳐야 파일에 존재하는 byte들을 문자의 형태로 읽을 수 있다.
** 우리가 작성하는 문자 형식을 stream이 작성할 수 있는 byte 형식으로 변경해야 하는데, OutputStreamWriter를 사용하여 해당 작업을 수행 할 수 있음.

[source, java]
----
// InputStreamReader
public int read(char cbuf[], int offset, int length) throws IOException {
    return sd.read(cbuf, offset, length); // StreamDecoder sd;
}
----
[source, java]
----
// StreamDecodeer
public int read(char cbuf[], int offset, int length) throws IOException {
    int off = offset;
    int len = length;
    synchronized (lock) {
        ensureOpen();
        if ((off < 0) || (off > cbuf.length) || (len < 0) ||
            ((off + len) > cbuf.length) || ((off + len) < 0)) {
            throw new IndexOutOfBoundsException();
        }
        if (len == 0)
            return 0;

        int n = 0;

        if (haveLeftoverChar) {
            // Copy the leftover char into the buffer
            cbuf[off] = leftoverChar;
            off++; len--;
            haveLeftoverChar = false;
            n = 1;
            if ((len == 0) || !implReady())
                // Return now if this is all we can produce w/o blocking
                return n;
        }

        if (len == 1) {
            // Treat single-character array reads just like read()
            int c = read0();
            if (c == -1)
                return (n == 0) ? -1 : n;
            cbuf[off] = (char)c;
            return n + 1;
        }

        return n + implRead(cbuf, off, off + len);
    }
}

int implRead(char[] cbuf, int off, int end) throws IOException {

    // In order to handle surrogate pairs, this method requires that
    // the invoker attempt to read at least two characters.  Saving the
    // extra character, if any, at a higher level is easier than trying
    // to deal with it here.
    assert (end - off > 1);

    CharBuffer cb = CharBuffer.wrap(cbuf, off, end - off);
    if (cb.position() != 0)
    // Ensure that cb[0] == cbuf[off]
    cb = cb.slice();

    boolean eof = false;
    for (;;) {
    CoderResult cr = decoder.decode(bb, cb, eof);
    if (cr.isUnderflow()) {
        if (eof)
            break;
        if (!cb.hasRemaining())
            break;
        if ((cb.position() > 0) && !inReady())
            break;          // Block at most once
        int n = readBytes();
        if (n < 0) {
            eof = true;
            if ((cb.position() == 0) && (!bb.hasRemaining()))
                break;
            decoder.reset();
        }
        continue;
    }
    if (cr.isOverflow()) {
        assert cb.position() > 0;
        break;
    }
    cr.throwException();
    }

    if (eof) {
    // ## Need to flush decoder
    decoder.reset();
    }

    if (cb.position() == 0) {
        if (eof)
            return -1;
        assert false;
    }
    return cb.position();
}
----

[source, java]
----
// OutputStreamWriter
public void write(char cbuf[], int off, int len) throws IOException {
    se.write(cbuf, off, len); // StreamEncoder se;
}
----

[source, java]
----
// StreamEncoder
public void write(char cbuf[], int off, int len) throws IOException {
    synchronized (lock) {
        ensureOpen();
        if ((off < 0) || (off > cbuf.length) || (len < 0) ||
            ((off + len) > cbuf.length) || ((off + len) < 0)) {
            throw new IndexOutOfBoundsException();
        } else if (len == 0) {
            return;
        }
        implWrite(cbuf, off, len);
    }
}

void implWrite(CharBuffer cb) throws IOException {
    if (haveLeftoverChar) {
        flushLeftoverChar(cb, false);
    }

    while (cb.hasRemaining()) {
        CoderResult cr = encoder.encode(cb, bb, false);
        if (cr.isUnderflow()) {
            assert (cb.remaining() <= 1) : cb.remaining();
            if (cb.remaining() == 1) {
                haveLeftoverChar = true;
                leftoverChar = cb.get();
            }
            break;
        }
        if (cr.isOverflow()) {
            assert bb.position() > 0;
            writeBytes();
            continue;
        }
        cr.throwException();
    }
}
----

=== Stream 종료

* I/O Stream을 사용하는 경우에 `close()` 한다.
** 만약 I/O Stream을 닫지 않는다면 위에서 작성된 오류들을 만나게 될 수 있다.
*** 웹 상에서 동시에 다른 자원에 접근 할 시, 사용하지 않는 자원을 잠금해제하지 않아서, 자원에 접근 하지 못하여, Starvation에 빠지는 경우
*** 악의적인 사용자가 `서비스 거부`를 발생시킬 수 있는 가능성이 존재한다.
*** File Descriptor Table내 공간이 부족하여 프로그램에서 새로운 자원의 주소를 사용하지 못하고 이를 해결하기 위해서는 시스템을 종료해야하는 문제가 발생하는데 이렇게 주기적으로 시스템을 종료하다 보면 사용자의 신뢰를 잃을 수 있다.
