= 학습 이유

. MVC 구조로 서비스를 구현, 프로그래머의 개입없이 동작을 구현하기 위해 학습의 필요성을 느낌
. Spring에서 사용되는 IOC를 경험하기 위해서 학습을 실시
  
= 학습 목차

. 의존성 주입 (Dependency Injection)
. Tomcat에서 Annotation을 활용한 의존성 주입
. 제어역전 (Invertion Of Control)
    
= 본문
    
== 의존성 주입 (Dependency Injection)

* 외부에서 클라이언트에게 서비스를 제공하는 것을 의미한다. 객체가 필요로 하는 것을 외부에서 객체로 전달하는 것을 의미한다.
* `A Class`가  `B Class`의 코드를 참조할 때, A는 B에 의존한다고 말할 수 있다. 여기에서 A가 클라이언트고 B가 서비스라고 볼 수 있다.
** 특정 클래스가 다른 클래스의 객체 혹은 요소들을 전달받는 것을 의존성 주입이라 할 수 있다.
** LSP 또한 객체를 전달할 때, 전달될 클래스의 상위 타입을 넣어 동일한 상속관계를 가지는 객체를 받을 수 있다는 것을 의미하므로 의존성이 주입되는 경우로 치부할 수 있다.
* Spring에서는 AutoWired Annotation을 받아, 의존성 주입의 관계를 명시한다.

. Constructor Injection
.. 생성자에서 다른 클래스의 객체 혹은 요소를 받아 의존관계(해당 클래스에서 다른 클래스의 요소를 사용)를 형성하는 것을 의미한다.
. Method Injection
.. 클래스에 정의된 특수한 메서드(Selector)를 통해서 다른 클래스의 객체 혹은 요소를 받아 의존관계(해당 클래스에서 다른 클래스의 요소를 사용)를 형성하는 것을 의미한다.
. Field Injection
.. Tomcat, Spring 등의 Container가 아닌 외부에서는 사용할 수 없는 방식이다?
.. 클래스에 존재하는 인스턴스 변수에 다른 클래스의 객체 혹은 요소를 받아서 사용한다. 전달받는 방식이 메서드(Selector)를 통해서 객체나 요소를 전달받기 때문에 Method Injection과 유사하다고 볼 수 있다.

== Tomcat에서 Annotation을 활용한 의존성 주입
  
* Java가 제공하는 Annotation 이외에도 @interface Annotation을 통해서 사용자가 클래스 또는 변수를 특정한 값으로 지정하여 사용 및 관리할 수 있다.
* 기본적으로 `@Retention`, `@Target` Annotation과 같이 사용된다.

* `@Retention`
** @interface Annotation의 적용 범위로 어떠한 시점까지 사용될지 결정하는 옵션이다.
. RetentionPolicy.Class
.. Default 값으로 Compiler가 Class를 참조할 때까지만 유효한 범위로 설정한다.
. RetentionPolicy.Runtime
.. Compile 이후, Runtime에서도 JVM에서 참조가 가능한 범위로 설정한다.
. RetentionPolicy.Source
.. Compile 이전의 시점까지만 유효한 범위로 설정한다.

* `@Target`
**  @interface Annotation의 적용 위치를 결정하는 옵션이다.
. ElementType.TYPE: 클래스 및 인터페이스
. ElementType.FIELD: 클래스의 멤버 변수
. ElementType.PARAMETER: 매개변수
. ElementType.CONSTRUCTOR: 생성자
. ElementType.LOCAL_VARIABLE: 지역변수
. ElementType.ANNOTAION_TYPE: 어노테이션 타입
. ElementType.PACKAGE: 패키지
. ElementType.TYPE_PARAMETER: 타입 파라미터
. ElementType.TYPE_USE: 타입 사용

== 제어역전 (Invertion Of Control)

* 프로그래머가 객체의 생성, 의존성 주입을 실시하지 않아도 Application에서 해당 작업을 실시하는 것을 제어 역전이라고 부른다.
  
= 해결과정

[source, java]
----
@Target(value = {ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface RequestMapping {
    enum Method{
        POST,GET
    }

    String[] value();
    Method method() default Method.GET;

}
----

* 사용자가 생성하고 관리할 수 있는 Annotaion을 이용하여 클래스를 생성하였음, 이 클래스는 Annotaion이 사용된 클래스(@Target에 따라 변경될 수 있다.)의 Java Reflection을 사용해 클래스 타입에 붙어있는 Annotaion을 가지고 각 클래스를 구분하여 Map에 저장

** Java Reflection으로 클래스에 붙어있는 객체마다, 존재하는 Annotaion의 멤버 변수(필드)에 직접적으로 참조하기 때문에 이러한 부분에서 Field Injection이라고 말씀하신듯 하다.

[source, java]
----
try {
    for (Class<?> clazz : c) {
        BaseController controller = (BaseController) clazz.getConstructor().newInstance();

        for (String value : clazz.getAnnotation(RequestMapping.class).value()) {
            beanMap.put(clazz.getAnnotation(RequestMapping.class).method() + "-" + value, controller);
        }
    }

} catch (InstantiationException | IllegalAccessException | IllegalArgumentException |
            InvocationTargetException | NoSuchMethodException e) {
    log.error("Controller Factory : {}", e.getMessage());
}
----

* 아래의 예제에서 작성된 Annotation의 필드 값들을 Reflection으로 참조하는 것을 확인할 수 있었음.
* 사용자 생성 Annotaion @interface를 통해, 생성된 Annotaion의 값(Field Injection)을 특정 클래스로 연관 지어 Map에 저장하는 방식으로 제어 역전을 구현한다.

[source, java]
----
@RequestMapping(method = RequestMapping.Method.GET, value = {"/index.do"})
public class IndexController implements BaseController {

    private final ProductService productService = new ProductServiceImpl(new ProductRepositoryImpl());

    @Override
    public String execute(HttpServletRequest req, HttpServletResponse resp) {
        return "shop/main/index";
    }
}
----

* Java Reflection에서 Scan을 진행할 때, 정해진 클래스들만 찾는 것을 지정해 주는 지정자 역할을 수행한다. 사용할 클래스들이 Scan을 통해서 지정되기 때문에, Reflection에서 잘못된 클래스를 찾는 불상사를 예방할 수 있다.

[source, java]
----
@HandlesTypes(
        value = {
                BaseController.class
        }
)
----
